/**
 * Buncf Router - Client-side Provider
 *
 * Handles navigation, route matching, and dynamic page importing on the client.
 */

import React, {
  useState,
  useEffect,
  type ReactNode,
  type ComponentType,
} from 'react';
import { routerStore, type RouteState } from './client';

export interface PageProps {
  params: Record<string, string>;
  query: Record<string, string>;
}

export interface RouterProviderProps {
  /**
   * Root layout component
   * Wraps every page
   */
  layout?: ComponentType<{ children: ReactNode }>;

  /**
   * Map of route patterns to dynamic imports
   * Automatically generated by buncf dev
   */
  routes?: Record<string, () => Promise<{ default: ComponentType<any> }>>;
}

/**
 * 404 Page Component
 */
function NotFoundPage() {
  return (
    <div
      style={{ padding: '40px', fontFamily: 'sans-serif', textAlign: 'center' }}
    >
      <h1 style={{ color: '#e11d48', fontSize: '2rem' }}>
        404 - Page Not Found
      </h1>
      <p style={{ color: '#4b5563' }}>
        The page you are looking for does not exist.
      </p>
      <a href="/" style={{ color: '#2563eb', textDecoration: 'underline' }}>
        Go Home
      </a>
    </div>
  );
}

/**
 * Error Page Component
 * Shown when setup is incorrect or page fails to load
 */
function ErrorPage({ error }: { error: Error }) {
  return (
    <div style={{ padding: '40px', fontFamily: 'sans-serif' }}>
      <h1 style={{ color: '#e11d48' }}>Something went wrong</h1>
      <pre
        style={{
          background: '#f3f4f6',
          padding: '20px',
          borderRadius: '8px',
          overflowX: 'auto',
        }}
      >
        {error.message}
      </pre>
    </div>
  );
}

/**
 * Buncf Router Component
 *
 * Usage:
 * ```tsx
 * import { BuncfRouter } from "buncf/router";
 * import Layout from "./_layout";
 *
 * // Routes are usually auto-injected by the build process
 * // based on file-system structure
 *
 * <BuncfRouter layout={Layout} />
 * ```
 */
export function BuncfRouter({
  layout: Layout,
  routes = {},
}: RouterProviderProps) {
  const [route, setRoute] = useState<RouteState>(routerStore.getState());
  const [PageComponent, setPageComponent] = useState<ComponentType<any> | null>(
    null,
  );
  const [error, setError] = useState<Error | null>(null);
  const [loading, setLoading] = useState(false);

  // Subscribe to router store updates
  useEffect(() => {
    const unsubscribe = routerStore.subscribe((state) => {
      setRoute(state);
      loadPage(state.pathname);
    });
    return () => {
      unsubscribe();
    };
  }, []);

  // Initial load
  useEffect(() => {
    loadPage(route.pathname);
  }, []);

  async function loadPage(pathname: string) {
    setError(null);
    setLoading(true);

    try {
      // 1. Find matching route
      // This is a simplified client-side matcher.
      // Ideally we reuse the server's match data if available from window.__BUNCF_ROUTE__
      // or implement full matching logic here.

      // For now, let's assume we can resolve the import key mostly directly or through simple map
      // In a real implementation, we need the route manifest passed from server.

      // Heuristic: Try exact match first
      let importer = routes[pathname];

      // Try resolving index
      if (!importer && pathname === '/') importer = routes['/index'];

      // TODO: Add proper dynamic route matching (client-side)
      // For now we rely on what we can find in the map

      if (!importer) {
        // Retry with simple mapping logic for now
        // /about -> /about
        // /users/123 -> /users/[id] ?? Hard without manifest

        // Use injected route data if available
        const injected = (window as any).__BUNCF_ROUTE__;
        if (injected && injected.pathname === pathname && injected.filePath) {
          // We might need to map filePath back to route key
        }

        setPageComponent(() => NotFoundPage);
        return;
      }

      // 2. Import page component
      const module = await importer();
      if (!module.default) {
        throw new Error(
          `Page at ${pathname} does not export a default component`,
        );
      }

      setPageComponent(() => module.default);
    } catch (err: any) {
      console.error('[buncf] Failed to load page:', err);
      setError(err);
    } finally {
      setLoading(false);
    }
  }

  // Render
  if (error) {
    if (Layout) {
      return (
        <Layout>
          <ErrorPage error={error} />
        </Layout>
      );
    }
    return <ErrorPage error={error} />;
  }

  const Content = PageComponent ? (
    <PageComponent params={route.params} query={route.query} />
  ) : (
    // Only show loading if taking too long, or custom loading
    <div />
  );

  if (Layout) {
    return <Layout>{Content}</Layout>;
  }

  return Content;
}
