/**
 * Type Generator - Creates TypeScript declaration files for API routes
 */

import * as fs from "fs";
import * as path from "path";
import { type RouteTypeInfo, groupRoutesByPath } from "./api-scanner";

/**
 * Generates the content of .buncf/api-types.d.ts
 */
export function generateTypesContent(routes: RouteTypeInfo[]): string {
  const grouped = groupRoutesByPath(routes);

  const lines: string[] = [
    "/**",
    " * Auto-generated by buncf",
    " * Do not edit this file manually",
    " */",
    "",
    "export interface ApiRoutes {"
  ];

  for (const [routePath, methods] of grouped) {
    lines.push(`  "${routePath}": {`);

    for (const method of methods) {
      const parts: string[] = [];

      if (method.params && method.params !== "{}" && method.params !== "Record<string, string>") {
        parts.push(`params: ${method.params}`);
      }
      if (method.body) {
        parts.push(`body: ${method.body}`);
      }
      if (method.response && method.response !== "unknown") {
        parts.push(`response: ${method.response}`);
      } else {
        parts.push(`response: unknown`);
      }

      lines.push(`    ${method.method}: { ${parts.join("; ")} };`);
    }

    lines.push(`  };`);
  }

  lines.push("}");
  lines.push("");

  return lines.join("\n");
}

/**
 * Generates .buncf/api-types.d.ts from scanned route info
 */
export async function generateApiTypes(routes: RouteTypeInfo[], outputDir: string): Promise<void> {
  const content = generateTypesContent(routes);
  const outputPath = path.join(outputDir, "api-types.d.ts");

  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  await Bun.write(outputPath, content);
}
